### ISSUE TITLE
Trakt 2.0

### ISSUE THREAD

**Issue by pixibuex** [trakt/Plex-Trakt-Scrobbler#153]
Seems the scrobbler is not compatible with Trakt 2.0. Any news?

**Comment by SourSkittles** [comment]
any info on when the next update to this is going to happen? scrobbling barely works it seems as of right now, as I've watched stuff for the past few days and it doesn't scrobble a single one of them, I pretty much have to go and manually mark them now...

**Comment by mrfacu87** [comment]
I have been having issues since the upgrade to v2 as well. Yesterday, I upgraded the Trakt plugin to version 0.9.0.4-beta and restarted the PMS. After that, scrobbling seems to be working fine for me. There are several shows that did not scrobble during the down time, I will wait for the sync feature on the next update and see if they sync, which according to fuzeman should be any time soon :D

**Comment by BrutuZ** [comment]
Hopefully the updated version will make use of the [watched_at](http://docs.trakt.apiary.io/reference/sync/add-to-history) metadata when syncing to mark the items at their proper watch dates instead of marking them all as watched at the time the sync occurred.
Plex makes this information available as the **lastViewedAt** parameter under the item's *MediaContainer\Video* metadata in [Epoch](http://www.epochconverter.com) format

**Comment by matrixagent** [comment]
What @BrutuZ writes is exactly what I'm hoping for, I've actually disabled all syncing etc. in the plugin and am planning to only re-enable it once the plugin is making use of these features so I'm getting clean data into trakt.

**Comment by dewey** [comment]
I second these last two comments. I disabled it and I'd love to see the accurate data return.

**Comment by fuzeman** [comment]
**v0.9.1.1-beta** has been released: https://forums.plex.tv/index.php/topic/102818-rel-trakt/page-23#entry810730 *(this release sends "watched_at" and "collected_at" parameters when syncing with trakt)*.

Known issues:
 - Syncing can fail as a result of a 504 error returned from the trakt API
 - Some shows are missing seasons/episodes or have invalid data on trakt *(this problem is being worked on, not sure on the current status though)*

**Comment by sofianeh** [comment]
Is the use of OAuth planned? I can't find it within 0.9.1.1-beta release

**Comment by fuzeman** [comment]
@sofianeh it isn't really possible to use OAuth in a Plex plugin (no web browser access), permission was granted to authenticate with a username + password instead.

**Comment by daften** [comment]
You only need the web browser the first time though, so why wouldn't it be possible, if you set it up via the web interface?

**Comment by sofianeh** [comment]
I totally agree with @daften

**Comment by BrutuZ** [comment]
Using the beta seems most of the scrobbles were updated just fine. It did scrobble 2 episodes to the time of sync, and I haven't even watched one of them yet (it hasn't aired).

I got some errors on the log, it was going fine with HTTP requests returning 200 as they should until
```
2015-01-03 17:07:18,838 (11e4) :  DEBUG (logkit:13) - [requests.packages.urllib3.connectionpool] "GET /sync/watched/shows HTTP/1.1" 200 None
2015-01-03 17:07:36,178 (11e4) :  DEBUG (logkit:13) - [requests.packages.urllib3.connectionpool] "GET /sync/ratings/shows HTTP/1.1" 502 None
2015-01-03 17:07:36,183 (11e4) :  DEBUG (logkit:13) - [trakt.interfaces.base] response returned "text/html; charset=UTF-8" content, falling back to raw data
2015-01-03 17:07:36,184 (11e4) :  WARNING (logkit:19) - [trakt.interfaces.base] request failed: Unknown - "Unknown" (code: 502)
2015-01-03 17:07:36,187 (11e4) :  WARNING (logkit:19) - [plugin.sync.sync_base] Unable to fetch ratings
2015-01-03 17:07:36,193 (11e4) :  WARNING (logkit:19) - [plugin.sync.push] Unable to construct merged library from trakt
2015-01-03 17:07:36,207 (1c38) :  INFO (logkit:16) - [plugin.sync.sync_base] Task "(u'push', u'1')" finished - success: False, start: 2015-01-03 19:07:02.588000, elapsed: 0:00:33.607000
```

**Comment by fuzeman** [comment]
**v0.9.1.2-beta** has been released: https://forums.plex.tv/index.php/topic/102818-rel-trakt/page-23#entry812374, this fixes a number of bugs that have been reported recently.

------------------

@daften I'm guessing by "web interface" you are talking about Plex/Web - The plugin still has no ability to redirect the user to a URL, this includes when the channel is being used via Plex/Web.

To avoid entering credentials in the plugin, the best you can do currently is request a token manually *(http://docs.trakt.apiary.io/#reference/authentication-media-centers/login/get-user-token)* and update the plugin ```Dict``` manually with that token.

I doubt OAuth will be possible/available any time soon...

-------------------------

@BrutuZ yeah, I've found the servers to be a bit up and down currently. I can't really do much to fix that and having the plugin retry requests would only cause more load to the API servers.

**Comment by scottrobertson** [comment]
Running latest beta, all syncs are failing for me too. Have Trakt removed the ability for clients to use Username/Password, or is it still there?

**Comment by mchiareli** [comment]
I can't sync with the new beta version too. Where can I find the log files on mac os?

**Comment by scottrobertson** [comment]
@mchiareli `/Library/Application Support/Plex Media Server/Logs/PMS Plugin Logs` i imagine.

**Comment by ppgb** [comment]
Strange thing happened. I watched a movie on Plex from beginning to end, and it got scrobbled 4 times - it appeared 4 times on top of my trakt watch history!!

**Comment by fuzeman** [comment]
@scottrobertson username/password authentication is still available.

With the API servers having problems lately, it's possible authentication might of failed when the plugin tried to start up. Try restarting Plex Media Server (so the plugin restarts) and send the full ```com.plexapp.plugins.trakttv.log``` file if the error is still happening.

----------------------

@ppgb which client were you playing the movie on (PHT, Plex/Web, DLNA, etc..)?

Sending your log files to me would help as well, see https://github.com/fuzeman/Plex-Trakt-Scrobbler/wiki/Support#log-files for the location of them.

**Comment by SourSkittles** [comment]
same thing that happened to ppgb happened to me as well while watching a tv show, but instead of scrobbling 4 times it only scrobbled it twice.

http://pastebin.com/FyiszHy8

**Comment by ppgb** [comment]
@Dean, client was PHT, latest version on Windows 7. PMS is latest version on a Synology NAS.

**Comment by dean** [comment]
@pggb - I think you pinged the wrong person. :)

**Comment by ppgb** [comment]
Yes, I meant @fuzeman (Dean Gardiner) client was PHT, latest version on Windows 7. PMS is latest version on a Synology NAS.

**Comment by PGGB** [comment]
@dean I think you pinged the wrong person too.

**Comment by fuzeman** [comment]
Haha, maybe GitHub should display a warning when you mention someone outside the current conversation/repository :smile: 

-----------------------

Anyway, I've finally managed to reproduce the multi-scrobble issue, will have a hotfix released later today.

**Comment by SourSkittles** [comment]
@fuzeman any word on the fix? I just had this happen to me again after it not happening for several days but this time it scrobbled the show I was watching 18 times.

http://pastebin.com/Rmz49QC3

**Comment by fuzeman** [comment]
**v0.9.1.3-beta** has been released: https://forums.plex.tv/index.php/topic/102818-rel-trakt/page-25#entry816952, this should fix the duplicate/multiple scrobbles.

Please post your logs if you continue to find it scrobbling multiple times.

-------------

*There is a chance syncing could be causing duplication - will be looking into this closer over the next few days.*

**Comment by BrutuZ** [comment]
When syncing, the watched_at time is offset. Something between 6 and 8 hours for me.
I watched the media at **1420684463** epoch according to Plex, which translates to 02:34 GMT (00:34 on my local time), that's correct, however Trakt is displaying it as watched at 08:34.
I changed the Trakt site settings to my Time Zone, but at GMT -02:00 (DST), 08:34 is simply not possible.

I'm not sure if this issue is just another glitch of the new website that needs to be ironed out, or on the plugin's end (maybe something with the epoch time conversion to UTC), but thought it was worth mentioning.

My Activity Mode is set to Logging (the client I use is not compatible with WebSocket) and Sync to Run Every 6 hours.

**Comment by scottrobertson** [comment]
@BrutuZ the times dont seem to change on trakt.tv when you change the timestamp, i beleive it's an issue on their end. I think the scrobbler sends it in UTC.

**Comment by BrutuZ** [comment]
@scottrobertson My thoughts exactly, just thought it was worth mentioning. (so much thinking...)
We are using the beta branch to have it working so I'm not complaining, just pointing out a bug that is probably on their end, but maybe is worth a look just to be sure of that.

Trakt is quite bumpy after the transition, it almost feels like the Last.fm make-over years ago, except the changes are way more significant. They are working on it everyday, a couple days ago the option to delete your own account wasn't in the settings yet. It will take some time to get used to the new interface, is just a matter of patience.

**Comment by scottrobertson** [comment]
@BrutuZ trakt seems to be reporting the times correctly now. @fuzeman did you change anything, or was it trakt?

**Comment by SourSkittles** [comment]
@fuzeman well it was scrobbling most of the day, but idk why it just kinda stopped scrobbling all together it seems and I have to either play the video twice (second time near the end of the video) to get it to scrobble or I have to go and manually mark my shows...

This little problem has been a ongoing issue even before the 2.0 upgrade to trakt so I really dunno what the issue is :/ where sometimes it'll scrobble just fine but other times it'll just act like it's scrobbling but it'll never scrobble unless I rewatch the ending of said show/movie.

http://pastebin.com/EqKmdzbr

**Comment by BrutuZ** [comment]
Didn't have the same luck as @scottrobertson . Just watched something and it scrobbled 8 hours in the future :laughing:

If it is of any help for @fuzeman or anyone else, either on a fix or just insight on why this happens, I made the [log](http://pastebin.com/VN0i31rb) and a [screenshot](http://imgur.com/x4IUPV3) showing the discrepancies available.

**Comment by fuzeman** [comment]
**v0.9.1.6-beta** has been released: https://forums.plex.tv/index.php/topic/102818-rel-trakt/page-27#entry818966, this release fixes another cause of scrobble duplication and an issue in syncing which caused timestamps to be offset on trakt.tv (as mentioned above).

**Comment by SourSkittles** [comment]
running latest beta, it scrobbled one episode but after it seems to not be able to scrobble at all anymore..

http://pastebin.com/qAzFZEZM

**Comment by BrutuZ** [comment]
Sync offset does seem to have been fixed. ~~However Logging (Legacy) no longer scrobbles.
The debug log keeps reading websocket events despite it not being selected and the client not using the plex.tv login (it sends HTTP requests directly to the server's LAN IP).~~

I'll take that last part to the issue already open since it has nothing to do with Trakt 2.0.

**Comment by fuzeman** [comment]
**v0.9.1.7-beta** has been released: https://forums.plex.tv/index.php/topic/102818-rel-trakt/page-28#entry820611

**Comment by SourSkittles** [comment]
@fuzeman Dunno what just happened but it scrobbled a movie I hadn't watched in weeks (since it's not even on my computer anymore but some how was stuck on plex like all my movies have been doing for some odd reason) like 11 different times saying I was watching it as well, and it seems like it tried to scrobble a game of thrones episode as well for some unknown reason as I wasn't even watching anything and when I went on plex it said I watched 3 minutes of an episode when I haven't..

I'm the only one who can access all my shows/plex stuff so I know that no one else is doing this stuff as I have it all blocked off from being accessed by other computers on my network or any other network..

The last show I watched was the librarians which several hours ago..

http://pastebin.com/f6P1WC6g

**Comment by cvergne** [comment]
Hi !

Thanks for the dev of that plugin, but still have issues even with the beta :(
In fact, everything was working fine yesterday (only with TV shows, movies was not working), but today only "push" is working, not "pull".
I've updated my watchlist on my trakt.tv account earlier today, then my tv shows collection on plex. But push works (even if i have not whatched anything since previous working sync).
I'm using the last version (0.9.7-beta) of the plugin with last version of PMS.

You can find the complete log (i tried "push&pull" and "pull only", both failed, but log is for "pull only" here) : [log file](https://gist.githubusercontent.com/cvergne/0178b5fd3dd73b298080/raw/f90bca1da5d9f13596b138f14e82d70443f41b12/traktPMS.log)

Hope that will help you :)

**Comment by fuzeman** [comment]
@cvergne the trakt API is down currently (has been down/unreliable for the last 6 - 8 hours), so syncing and scrobbling probably won't work or will be very unreliable.

I'm currently working on better error messages when syncing fails, this will help to determine where the problem is (trakt.tv or the plugin).

**Comment by cvergne** [comment]
@fuzeman Thanks, that was the reason :) It's working fine now. I've searched a "status page" for Trakt API but not found :/

**Comment by ppgb** [comment]
Scrobbling stopped working after I upgraded to one of the latest betas.

**Comment by fuzeman** [comment]
**v0.9.1.9-beta** has been released: https://forums.plex.tv/index.php/topic/102818-rel-trakt/page-31#entry829615

**Comment by scottrobertson** [comment]
@fuzeman awesome work. Do you scrub any sensitive data before sending it to Sentry? If so, you could make it a public project, which would be quite awesome.

**Comment by fuzeman** [comment]
@scottrobertson mainly just exceptions are reported to sentry - local variables are removed and paths are all converted to be relative to the "Plug-ins" folder (so windows account names aren't stored).

I'm not sure about having the sentry project completely open (this could result in a few issues). I'll probably just share specific events that are relevant to issues reported on the github issue tracker.

**Comment by scottrobertson** [comment]
@fuzeman Awesome, thanks. It was mainly the first part I wanted to make sure about, the idea of it being public was just an idea :) I would be lost without Sentry!

**Comment by fuzeman** [comment]
**v0.9.1.10** has been released: https://forums.plex.tv/index.php/topic/102818-rel-trakt/page-32#entry831576 (numerous bug fixes :smile:)

**Comment by fuzeman** [comment]
**v0.9.1.11** has been released: https://forums.plex.tv/index.php/topic/102818-rel-trakt/page-33#entry834510

**Comment by fuzeman** [comment]
**v0.9.1.12-beta** has been released: https://forums.plex.tv/index.php/topic/102818-rel-trakt/page-34#entry837859, hopefully the final **v0.9.1** beta :smiley:

**Comment by fuzeman** [comment]
I've just released **v0.9.1** onto the stable branch now: https://forums.plex.tv/index.php/topic/102818-rel-trakt/page-35#entry841418

Closing this issue now :smiley:
