### ISSUE TITLE
Plex - Trakt Plugin - 'Server Error'

### ISSUE THREAD

**Issue by DGCupit** [trakt/Plex-Trakt-Scrobbler#274]
Windows 10 x64
Latest Plex Pass Server Release 0.9.15.4
Trakt Plugin 1.0.0.3-master

I followed the seemingly simple instructions for installing the plugin. Stopped Plex, opened the Plugin folder, placed the bundle there, restarted plex, and then clicked the Configure for the plugin.

I went to trakt.tv/pin/478, copied / pasted the key into the Trakt config, clicked Save. Done?

I noticed that the Trakt PIN page remains on the Pin/Next Step page. Should it have moved forward, as an ack that the plugin used the issued key?

Either way, I then went to the Trakt channel, click on Sync, and tried a Sync All. It sits for a few moments, and the progress does not proceed. I then went back out to the root of Trakt and noticed a message; The message given:

[Exception] Server Error - 'server error'

[com.plexapp.plugins.trakttv.txt](https://github.com/trakt/Plex-Trakt-Scrobbler/files/134988/com.plexapp.plugins.trakttv.txt)

**Comment by fuzeman** [comment]
This is an issue with the Trakt.tv API -  it was fixed yesterday (https://github.com/trakt/Plex-Trakt-Scrobbler/issues/273), but it appears to be back again.

Trakt should already be aware of these issues, so it will likely be fixed soon.

**Comment by DGCupit** [comment]
As of this morning, the error is still occurring.

**Comment by gdolla** [comment]
Good morning I'm trying to fix the issue now

**Comment by sundset** [comment]
I have this issue as well, updated latest Plex version (0.9.15.6) and tried both Trakt (Master: 1.0.0.5 and Beta: 1.0.0.2-beta)
I am Plex VIP and Trakt VIP. 

Any news about this issue?

**Comment by sundset** [comment]
Still have the same issue, only with plex... 

Seems strange that this is a trakt.tv API issue when the other integrations work perfectly?

**Comment by rectifyer** [comment]
Looks like the issue is specifically with retrieving episode ratings. Can you provide your username so I can test this out and get a fix implemented in the API?

**Comment by gdolla** [comment]
Sure it's Goldndolla or dolla plex..  Thank you and good morning

**Comment by sundset** [comment]
@rectifyer: My username is **sundset**

**Comment by DGCupit** [comment]
I'm still getting these errors:

ServerError: Server Error - "Server Error"
ConnectionError: HTTPSConnectionPool(host='api-v2-launch.trakt.tv',port=443): Max Retried Exceeded
ConnectionError: HTTPSConnectionPool(host-'sentry.skipthe.net',port=443) Max Retired Exceeded.

My username is DGCupit

**Comment by Kiplol** [comment]
I'm also unable to proceed past the authentication PIN.  Syncing seems to work great, but not scrobbling.  My Trakt username is **kiplol**.

**Comment by rectifyer** [comment]
@DGCupit since both of those hosts are failing to connect, that seems like a larger issue on your media center with blocking connections. Maybe a firewall or other app is blocking outgoing connections?

@sundset @gdolla thanks, I should have a fix later this afternoon so your ratings are correctly returned.

@Kiplol the PIN must have been accepted if you're able to sync data correctly. It might not be scrobbling if the item is incorrectly scanned into your local library. Also double check the settings are correctly enabled.

**Comment by DGCupit** [comment]
The trakt plug in Emby is working without issue. Not sure how similar their connections are. There's no intentional

**Comment by DGCupit** [comment]
The trakt plug in Emby is working without issue. Not sure how similar their connections are. There's no intentional blocking on. I do use OPENDNS as my dns, so I wonder if they're blocking the resolve.

**Comment by DGCupit** [comment]
rectifyer, can you give me an idea of the URL that it would be trying to connect to? I can try to do a ping ,etc and see what I get.

I'm not seeing anything that would be blocking the connection.

**Comment by rectifyer** [comment]
@DGCupit hard to say from the log file, but since both hostnames are failing it seems like a more general  connection issue. That was my guess anyway.

**Comment by daveyboy37** [comment]
Yeah I have been seeing the same "server error" message for several days now also.

**Comment by DGCupit** [comment]
Can someone clarify, after you copy/paste the pin from the web page and put it into the trakt plugin and click save, is the pin Web page supposed to move forward or acknowledge anything, because it does not do anything to indicate it's accepted the authentication.

**Comment by daveyboy37** [comment]
@DGCupit 
Not 100% sure but I don't think it is supposed to close or confirm.
In the meantime I have been messing with the settings. With EVERYTHING set to disabled except 
"Sync-Watched" everything runs fine and completes...As soon as ANY other option is set to enabled the whole thing brings up the server error.
