### ISSUE TITLE
Trakt account hasn't been authenticated - Sentry.skipthe.net connexion timed out

### ISSUE THREAD

**Issue by BlackyFox** [trakt/Plex-Trakt-Scrobbler#484]
Hi !
I'm having an issue with the Trakt plugin for plex. I'm based off a fresh install of Plex on Windows 10x64 and the current stable release of the plugin : 
 * Plex server 3.39.3
 * Plugin version : 1.3.2

When I try to authenticated using the trakt pin, nothing happens when I save the trakt plugin conf (with new pin entered).
I then get the error _Trakt account hasn't been authenticated_.
Plus, I am seeing the _Sentry.skipthe.net connexion timed out_ error too.

Attached is the _com.plexapp.plugins.trakttv_.
[com.plexapp.plugins.trakttv.log](https://github.com/trakt/Plex-Trakt-Scrobbler/files/1778798/com.plexapp.plugins.trakttv.log)

I also noticed that the plugin is marked as not capable by my Plex server version (under Plex settings -> Server -> plugins).

Finally, my Trakt ID is BlackyFox.

Thanks for the help!

**Comment by vecchiae** [comment]
Same problem here, new installation of this Trakt plugin on Freenas, Plugin version is 1.3.2.
From the log

MaxRetryError: HTTPSConnectionPool(host='sentry.skipthe.net', port=443): Max retries exceeded with url: /api/1/store/ (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x80d285410>: Failed to establish a new connection: [Errno 61] Connection refused'))

It seems that sentry.skipthe.net is down, and thus we cannot authenticate a new Pin.

**Comment by rectifyer** [comment]
I've reached out to the dev to see if there is anything that will break if any references to `sentry.skipthe.net` are removed. Has anyone attempted to update the code to do this? Pull requests welcome!

**Comment by animosity22** [comment]
Working now without that line of code. Just auth'ed and synced.

**Comment by BlackyFox** [comment]
@animosity22, can you give a bit more information about what files and lines you changed please?

**Comment by animosity22** [comment]
A fix was pushed as I didn't change anything -> https://github.com/trakt/Plex-Trakt-Scrobbler/issues/481

**Comment by BlackyFox** [comment]
My bad, I didn't got that.
So, with last update, I have been able to auth, but Sync failed -> Exception raised in sync task: Bad Gateway - "Server unavailable"

Here are the full logs since auth success: 
`2018-03-04 20:56:21,497 - plugin.managers.m_trakt.account  (1bb8) :  INFO (plugin.managers.m_trakt.account:1159) - Updated account authorization for <TraktAccount username: u'BlackyFox'>
2018-03-04 20:56:21,516 - root                             (1bb8) :  INFO (root:840) - 200 GET /video/trakt/:/prefs/set?pin=XXXXXXX (127.0.0.1) 11102.00ms
2018-03-04 20:56:28,181 - root                             (2338) :  INFO (root:840) - 304 GET /video/trakt (127.0.0.1) 18.00ms
2018-03-04 20:56:29,053 - root                             (1654) :  INFO (root:840) - 304 GET /video/trakt (127.0.0.1) 13.00ms
2018-03-04 20:56:29,082 - plex.objects.core.base           (1aa4) :  WARNING (plex.objects.core.base:1171) - [Section] Omitted attribute: scannedat
2018-03-04 20:56:29,084 - plex.objects.core.base           (1aa4) :  WARNING (plex.objects.core.base:1171) - [Section] Omitted attribute: scannedat
2018-03-04 20:56:29,086 - root                             (1aa4) :  INFO (root:840) - 200 GET /video/trakt/sync (127.0.0.1) 16.00ms
2018-03-04 20:56:29,118 - root                             (1604) :  INFO (root:840) - 200 GET /:/plugins/com.plexapp.plugins.trakttv/resources/icon-sync_down.png?t=1520193332 (127.0.0.1) 3.00ms
2018-03-04 20:56:29,135 - root                             (1d80) :  INFO (root:840) - 200 GET /:/plugins/com.plexapp.plugins.trakttv/resources/icon-sync_up.png?t=1520193332 (127.0.0.1) 3.00ms
2018-03-04 20:56:29,747 - plex.objects.core.base           (a98) :  WARNING (plex.objects.core.base:1171) - [Section] Omitted attribute: scannedat
2018-03-04 20:56:29,750 - plex.objects.core.base           (a98) :  WARNING (plex.objects.core.base:1171) - [Section] Omitted attribute: scannedat
2018-03-04 20:56:29,753 - root                             (a98) :  INFO (root:840) - 200 GET /video/trakt/sync (127.0.0.1) 16.00ms
2018-03-04 20:56:29,811 - plugin.sync.main                 (1e5c) :  INFO (plugin.sync.main:1159) - (0) Started
2018-03-04 20:56:29,813 - plugin.sync.modes.core.base.mode (1e5c) :  INFO (plugin.sync.modes.core.base.mode:1159) - Executing construct() on child: <plugin.sync.modes.fast_pull.movies.Movies object at 0x08FE5D50>
2018-03-04 20:56:29,819 - plex.objects.core.base           (1e5c) :  WARNING (plex.objects.core.base:1171) - [Section] Omitted attribute: scannedat
2018-03-04 20:56:29,819 - plex.objects.core.base           (1e5c) :  WARNING (plex.objects.core.base:1171) - [Section] Omitted attribute: scannedat
2018-03-04 20:56:29,849 - plugin.sync.modes.core.base.mode (1e5c) :  INFO (plugin.sync.modes.core.base.mode:1159) - Executing construct() on child: <plugin.sync.modes.fast_pull.shows.Shows object at 0x08FE5470>
2018-03-04 20:56:29,857 - plex.objects.core.base           (1e5c) :  WARNING (plex.objects.core.base:1171) - [Section] Omitted attribute: scannedat
2018-03-04 20:56:29,857 - plex.objects.core.base           (1e5c) :  WARNING (plex.objects.core.base:1171) - [Section] Omitted attribute: scannedat
2018-03-04 20:56:30,063 - plugin.sync.modes.core.base.mode (1e5c) :  INFO (plugin.sync.modes.core.base.mode:1159) - Executing construct() on child: <plugin.sync.modes.push.movies.Movies object at 0x081B50B0>
2018-03-04 20:56:30,066 - plex.objects.core.base           (1e5c) :  WARNING (plex.objects.core.base:1171) - [Section] Omitted attribute: scannedat
2018-03-04 20:56:30,068 - plex.objects.core.base           (1e5c) :  WARNING (plex.objects.core.base:1171) - [Section] Omitted attribute: scannedat
2018-03-04 20:56:30,069 - plugin.sync.modes.core.base.mode (1e5c) :  INFO (plugin.sync.modes.core.base.mode:1159) - Executing construct() on child: <plugin.sync.modes.push.shows.Shows object at 0x081B5030>
2018-03-04 20:56:30,072 - plex.objects.core.base           (1e5c) :  WARNING (plex.objects.core.base:1171) - [Section] Omitted attribute: scannedat
2018-03-04 20:56:30,073 - plex.objects.core.base           (1e5c) :  WARNING (plex.objects.core.base:1171) - [Section] Omitted attribute: scannedat
2018-03-04 20:56:30,802 - root                             (704) :  INFO (root:840) - 200 GET /video/trakt/sync/synchronize?account_id=1&t=1520193389.07 (127.0.0.1) 1022.00ms
2018-03-04 20:56:30,844 - plex.objects.core.base           (1d74) :  WARNING (plex.objects.core.base:1171) - [Section] Omitted attribute: scannedat
2018-03-04 20:56:30,845 - plex.objects.core.base           (1d74) :  WARNING (plex.objects.core.base:1171) - [Section] Omitted attribute: scannedat
2018-03-04 20:56:30,849 - root                             (1d74) :  INFO (root:840) - 200 GET /video/trakt/sync?account_id=1 (127.0.0.1) 17.00ms
2018-03-04 20:56:37,029 - trakt_sync.cache.sources.sync    (1e5c) :  INFO (trakt_sync.cache.sources.sync:1159) - Fetching "sync/ratings/movies"
2018-03-04 20:56:39,674 - trakt_sync.cache.sources.sync    (1e5c) :  INFO (trakt_sync.cache.sources.sync:1159) - Fetching "sync/watched/movies"
2018-03-04 20:56:41,717 - trakt_sync.cache.sources.sync    (1e5c) :  INFO (trakt_sync.cache.sources.sync:1159) - Fetching "sync/ratings/episodes"
2018-03-04 20:56:41,845 - trakt.interfaces.base            (1e5c) :  WARNING (trakt.interfaces.base:48) - Request failed: "GET /sync/ratings/episodes" - 502: "Server unavailable" (Bad Gateway)
2018-03-04 20:56:41,849 - plugin.sync.main                 (1e5c) :  WARNING (plugin.sync.main:1171) - Exception raised in sync task: Bad Gateway - "Server unavailable"
Traceback (most recent call last):
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\plugin\sync\main.py", line 173, in run_wrapper
    self.run()
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\plugin\sync\main.py", line 260, in run
    'stop'
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\plugin\sync\main.py", line 277, in _trigger
    func()
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\elapsed\main.py", line 64, in inner
    return func(*args, **kwargs)
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\plugin\sync\modes\full.py", line 23, in start
    self.trakt.refresh()
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\elapsed\main.py", line 64, in inner
    return func(*args, **kwargs)
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\plugin\sync\core\task\state\trakt_.py", line 110, in refresh
    self.changes = list(self.changes)
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\trakt_sync\cache\main.py", line 39, in refresh
    for result in source.refresh(username):
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\trakt_sync\cache\sources\sync.py", line 77, in refresh
    store = self.fetch(d, m)
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\trakt_sync\cache\sources\sync.py", line 165, in fetch
    return func(exceptions=True)
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\trakt\interfaces\base\__init__.py", line 20, in wrap
    return func(*args, **kwargs)
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\trakt\interfaces\sync\ratings.py", line 35, in episodes
    return self.get('episodes', store, rating, **kwargs)
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\trakt\interfaces\base\__init__.py", line 20, in wrap
    return func(*args, **kwargs)
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\trakt\interfaces\sync\ratings.py", line 18, in get
    **kwargs
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\trakt\interfaces\base\__init__.py", line 20, in wrap
    return func(*args, **kwargs)
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\trakt\interfaces\sync\core\mixins.py", line 30, in get
    items = self.get_data(response, **kwargs)
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\trakt\interfaces\base\__init__.py", line 81, in get_data
    raise ServerError(response)
ServerError: Bad Gateway - "Server unavailable"
2018-03-04 20:56:42,936 - sentry.errors                    (27e8) :  ERROR (sentry.errors:671) - Sentry responded with an error: MaxRetryError: HTTPSConnectionPool(host='sentry.skipthe.net', port=443): Max retries exceeded with url: /api/8/store/ (Caused by ConnectTimeoutError('Connection to sentry.skipthe.net timed out. (connect timeout=1)')) (url: https://sentry.skipthe.net/api/8/store/)
Traceback (most recent call last):
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\raven\transport\threaded_requests.py", line 26, in send_sync
    super(ThreadedRequestsHTTPTransport, self).send(data, headers)
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\raven\transport\requests.py", line 41, in send
    timeout=self.timeout
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\requests\api.py", line 110, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\requests\api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\requests\sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\raven\breadcrumbs.py", line 297, in send
    resp = real_send(self, request, *args, **kwargs)
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\requests\sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\requests\adapters.py", line 479, in send
    raise ConnectTimeout(e, request=request)
ConnectTimeout: MaxRetryError: HTTPSConnectionPool(host='sentry.skipthe.net', port=443): Max retries exceeded with url: /api/8/store/ (Caused by ConnectTimeoutError('Connection to sentry.skipthe.net timed out. (connect timeout=1)'))
2018-03-04 20:56:42,947 - sentry.errors.uncaught           (27e8) :  ERROR (sentry.errors.uncaught:696) - [u'Request failed: "GET /sync/ratings/episodes" - 502: "Server unavailable" (Bad Gateway)']
2018-03-04 20:56:43,950 - sentry.errors                    (27e8) :  ERROR (sentry.errors:671) - Sentry responded with an error: MaxRetryError: HTTPSConnectionPool(host='sentry.skipthe.net', port=443): Max retries exceeded with url: /api/8/store/ (Caused by ConnectTimeoutError('Connection to sentry.skipthe.net timed out. (connect timeout=1)')) (url: https://sentry.skipthe.net/api/8/store/)
Traceback (most recent call last):
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\raven\transport\threaded_requests.py", line 26, in send_sync
    super(ThreadedRequestsHTTPTransport, self).send(data, headers)
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\raven\transport\requests.py", line 41, in send
    timeout=self.timeout
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\requests\api.py", line 110, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\requests\api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\requests\sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\raven\breadcrumbs.py", line 297, in send
    resp = real_send(self, request, *args, **kwargs)
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\requests\sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\requests\adapters.py", line 479, in send
    raise ConnectTimeout(e, request=request)
ConnectTimeout: MaxRetryError: HTTPSConnectionPool(host='sentry.skipthe.net', port=443): Max retries exceeded with url: /api/8/store/ (Caused by ConnectTimeoutError('Connection to sentry.skipthe.net timed out. (connect timeout=1)'))
2018-03-04 20:56:43,956 - sentry.errors.uncaught           (27e8) :  ERROR (sentry.errors.uncaught:696) - [u'Exception raised in sync task: Bad Gateway - "Server unavailable"', u'  File "Plug-ins\\Trakttv.bundle\\Contents\\Libraries\\Shared\\plugin\\sync\\main.py", line 173, in run_wrapper', u'  File "Plug-ins\\Trakttv.bundle\\Contents\\Libraries\\Shared\\plugin\\sync\\main.py", line 260, in run', u'  File "Plug-ins\\Trakttv.bundle\\Contents\\Libraries\\Shared\\plugin\\sync\\main.py", line 277, in _trigger', u'  File "Plug-ins\\Trakttv.bundle\\Contents\\Libraries\\Shared\\elapsed\\main.py", line 64, in inner', u'  File "Plug-ins\\Trakttv.bundle\\Contents\\Libraries\\Shared\\plugin\\sync\\modes\\full.py", line 23, in start', u'  File "Plug-ins\\Trakttv.bundle\\Contents\\Libraries\\Shared\\elapsed\\main.py", line 64, in inner', u'  File "Plug-ins\\Trakttv.bundle\\Contents\\Libraries\\Shared\\plugin\\sync\\core\\task\\state\\trakt_.py", line 110, in refresh', u'  File "Plug-ins\\Trakttv.bundle\\Contents\\Libraries\\Shared\\trakt_sync\\cache\\main.py", line 39, in refresh', u'  File "Plug-ins\\Trakttv.bundle\\Contents\\Libraries\\Shared\\trakt_sync\\cache\\sources\\sync.py", line 77, in refresh', u'  File "Plug-ins\\Trakttv.bundle\\Contents\\Libraries\\Shared\\trakt_sync\\cache\\sources\\sync.py", line 165, in fetch', u'  File "Plug-ins\\Trakttv.bundle\\Contents\\Libraries\\Shared\\trakt\\interfaces\\base\\__init__.py", line 20, in wrap', u'  File "Plug-ins\\Trakttv.bundle\\Contents\\Libraries\\Shared\\trakt\\interfaces\\sync\\ratings.py", line 35, in episodes', u'  File "Plug-ins\\Trakttv.bundle\\Contents\\Libraries\\Shared\\trakt\\interfaces\\base\\__init__.py", line 20, in wrap', u'  File "Plug-ins\\Trakttv.bundle\\Contents\\Libraries\\Shared\\trakt\\interfaces\\sync\\ratings.py", line 18, in get', u'  File "Plug-ins\\Trakttv.bundle\\Contents\\Libraries\\Shared\\trakt\\interfaces\\base\\__init__.py", line 20, in wrap', u'  File "Plug-ins\\Trakttv.bundle\\Contents\\Libraries\\Shared\\trakt\\interfaces\\sync\\core\\mixins.py", line 30, in get', u'  File "Plug-ins\\Trakttv.bundle\\Contents\\Libraries\\Shared\\trakt\\interfaces\\base\\__init__.py", line 81, in get_data']
2018-03-04 20:56:45,509 - plugin.core.backup.sources.database (1e5c) :  INFO (plugin.core.backup.sources.database:1159) - [trakt\1] Backing up database to u'C:\\Users\\Nuc\\AppData\\Local\\Plex Media Server\\Plug-in Support\\Data\\com.plexapp.plugins.trakttv\\Backups\\trakt\\1.bgr\\2018\\03\\04_205645_27.db'
2018-03-04 20:56:45,528 - plugin.sync.main                 (1e5c) :  INFO (plugin.sync.main:1159) - (0) Done
2018-03-04 20:56:45,996 - root                             (2660) :  INFO (root:840) - 200 GET /video/trakt/:/prefs (127.0.0.1) 16.00ms
2018-03-04 20:57:02,490 - plugin.modules.migrations.account (6f0) :  INFO (plugin.modules.migrations.account:1159) - Plex Token: environment
2018-03-04 20:57:02,540 - root                             (6f0) :  INFO (root:840) - 200 GET /video/trakt/:/prefs/set?scrobble_names=user1%40email.com (127.0.0.1) 57.00ms
2018-03-04 20:57:06,115 - root                             (27a0) :  INFO (root:840) - 200 GET /video/trakt (127.0.0.1) 18.00ms
2018-03-04 20:57:07,332 - root                             (adc) :  INFO (root:840) - 304 GET /video/trakt (127.0.0.1) 15.00ms
2018-03-04 20:57:07,371 - plex.objects.core.base           (13e4) :  WARNING (plex.objects.core.base:1171) - [Section] Omitted attribute: scannedat
2018-03-04 20:57:07,372 - plex.objects.core.base           (13e4) :  WARNING (plex.objects.core.base:1171) - [Section] Omitted attribute: scannedat
2018-03-04 20:57:07,377 - root                             (13e4) :  INFO (root:840) - 200 GET /video/trakt/sync (127.0.0.1) 20.00ms
2018-03-04 20:57:16,194 - plex.objects.core.base           (16b4) :  WARNING (plex.objects.core.base:1171) - [Section] Omitted attribute: scannedat
2018-03-04 20:57:16,196 - plex.objects.core.base           (16b4) :  WARNING (plex.objects.core.base:1171) - [Section] Omitted attribute: scannedat
2018-03-04 20:57:16,198 - root                             (16b4) :  INFO (root:840) - 200 GET /video/trakt/sync (127.0.0.1) 21.00ms
2018-03-04 20:57:16,249 - plugin.sync.main                 (1e5c) :  INFO (plugin.sync.main:1159) - (0) Started
2018-03-04 20:57:16,250 - plugin.sync.modes.core.base.mode (1e5c) :  INFO (plugin.sync.modes.core.base.mode:1159) - Executing construct() on child: <plugin.sync.modes.fast_pull.movies.Movies object at 0x088E0230>
2018-03-04 20:57:16,255 - plex.objects.core.base           (1e5c) :  WARNING (plex.objects.core.base:1171) - [Section] Omitted attribute: scannedat
2018-03-04 20:57:16,256 - plex.objects.core.base           (1e5c) :  WARNING (plex.objects.core.base:1171) - [Section] Omitted attribute: scannedat
2018-03-04 20:57:16,257 - plugin.sync.modes.core.base.mode (1e5c) :  INFO (plugin.sync.modes.core.base.mode:1159) - Executing construct() on child: <plugin.sync.modes.fast_pull.shows.Shows object at 0x088E0130>
2018-03-04 20:57:16,262 - plex.objects.core.base           (1e5c) :  WARNING (plex.objects.core.base:1171) - [Section] Omitted attribute: scannedat
2018-03-04 20:57:16,262 - plex.objects.core.base           (1e5c) :  WARNING (plex.objects.core.base:1171) - [Section] Omitted attribute: scannedat
2018-03-04 20:57:16,275 - plugin.sync.modes.core.base.mode (1e5c) :  INFO (plugin.sync.modes.core.base.mode:1159) - Executing construct() on child: <plugin.sync.modes.push.movies.Movies object at 0x088E02F0>
2018-03-04 20:57:16,279 - plex.objects.core.base           (1e5c) :  WARNING (plex.objects.core.base:1171) - [Section] Omitted attribute: scannedat
2018-03-04 20:57:16,280 - plex.objects.core.base           (1e5c) :  WARNING (plex.objects.core.base:1171) - [Section] Omitted attribute: scannedat
2018-03-04 20:57:16,280 - plugin.sync.modes.core.base.mode (1e5c) :  INFO (plugin.sync.modes.core.base.mode:1159) - Executing construct() on child: <plugin.sync.modes.push.shows.Shows object at 0x088E0950>
2018-03-04 20:57:16,285 - plex.objects.core.base           (1e5c) :  WARNING (plex.objects.core.base:1171) - [Section] Omitted attribute: scannedat
2018-03-04 20:57:16,286 - plex.objects.core.base           (1e5c) :  WARNING (plex.objects.core.base:1171) - [Section] Omitted attribute: scannedat
2018-03-04 20:57:16,463 - trakt.interfaces.base            (1e5c) :  WARNING (trakt.interfaces.base:48) - Request failed: "GET /sync/last_activities" - 502: "Server unavailable" (Bad Gateway)
2018-03-04 20:57:16,467 - plugin.sync.main                 (1e5c) :  WARNING (plugin.sync.main:1171) - Exception raised in sync task: Bad Gateway - "Server unavailable"
Traceback (most recent call last):
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\plugin\sync\main.py", line 173, in run_wrapper
    self.run()
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\plugin\sync\main.py", line 260, in run
    'stop'
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\plugin\sync\main.py", line 277, in _trigger
    func()
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\elapsed\main.py", line 64, in inner
    return func(*args, **kwargs)
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\plugin\sync\modes\full.py", line 23, in start
    self.trakt.refresh()
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\elapsed\main.py", line 64, in inner
    return func(*args, **kwargs)
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\plugin\sync\core\task\state\trakt_.py", line 110, in refresh
    self.changes = list(self.changes)
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\trakt_sync\cache\main.py", line 39, in refresh
    for result in source.refresh(username):
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\trakt_sync\cache\sources\sync.py", line 41, in refresh
    activities = Trakt['sync'].last_activities(exceptions=True)
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\trakt\interfaces\base\__init__.py", line 20, in wrap
    return func(*args, **kwargs)
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\trakt\interfaces\sync\__init__.py", line 36, in last_activities
    **kwargs
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\trakt\interfaces\base\__init__.py", line 81, in get_data
    raise ServerError(response)
ServerError: Bad Gateway - "Server unavailable"
2018-03-04 20:57:16,483 - plugin.core.backup.sources.database (1e5c) :  INFO (plugin.core.backup.sources.database:1159) - [trakt\1] Backing up database to u'C:\\Users\\Nuc\\AppData\\Local\\Plex Media Server\\Plug-in Support\\Data\\com.plexapp.plugins.trakttv\\Backups\\trakt\\1.bgr\\2018\\03\\04_205716_28.db'
2018-03-04 20:57:16,506 - plugin.sync.main                 (1e5c) :  INFO (plugin.sync.main:1159) - (0) Done
2018-03-04 20:57:17,246 - root                             (111c) :  INFO (root:840) - 200 GET /video/trakt/sync/synchronize?account_id=1&t=1520193427.36 (127.0.0.1) 1024.00ms
2018-03-04 20:57:17,267 - plex.objects.core.base           (1888) :  WARNING (plex.objects.core.base:1171) - [Section] Omitted attribute: scannedat
2018-03-04 20:57:17,269 - plex.objects.core.base           (1888) :  WARNING (plex.objects.core.base:1171) - [Section] Omitted attribute: scannedat
2018-03-04 20:57:17,273 - root                             (1888) :  INFO (root:840) - 200 GET /video/trakt/sync?account_id=1 (127.0.0.1) 16.00ms
2018-03-04 20:57:17,469 - sentry.errors                    (27e8) :  ERROR (sentry.errors:671) - Sentry responded with an error: MaxRetryError: HTTPSConnectionPool(host='sentry.skipthe.net', port=443): Max retries exceeded with url: /api/8/store/ (Caused by ConnectTimeoutError('Connection to sentry.skipthe.net timed out. (connect timeout=1)')) (url: https://sentry.skipthe.net/api/8/store/)
Traceback (most recent call last):
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\raven\transport\threaded_requests.py", line 26, in send_sync
    super(ThreadedRequestsHTTPTransport, self).send(data, headers)
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\raven\transport\requests.py", line 41, in send
    timeout=self.timeout
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\requests\api.py", line 110, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\requests\api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\requests\sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\raven\breadcrumbs.py", line 297, in send
    resp = real_send(self, request, *args, **kwargs)
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\requests\sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\requests\adapters.py", line 479, in send
    raise ConnectTimeout(e, request=request)
ConnectTimeout: MaxRetryError: HTTPSConnectionPool(host='sentry.skipthe.net', port=443): Max retries exceeded with url: /api/8/store/ (Caused by ConnectTimeoutError('Connection to sentry.skipthe.net timed out. (connect timeout=1)'))
2018-03-04 20:57:17,476 - sentry.errors.uncaught           (27e8) :  ERROR (sentry.errors.uncaught:696) - [u'Request failed: "GET /sync/last_activities" - 502: "Server unavailable" (Bad Gateway)']
2018-03-04 20:57:18,479 - sentry.errors                    (27e8) :  ERROR (sentry.errors:671) - Sentry responded with an error: MaxRetryError: HTTPSConnectionPool(host='sentry.skipthe.net', port=443): Max retries exceeded with url: /api/8/store/ (Caused by ConnectTimeoutError('Connection to sentry.skipthe.net timed out. (connect timeout=1)')) (url: https://sentry.skipthe.net/api/8/store/)
Traceback (most recent call last):
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\raven\transport\threaded_requests.py", line 26, in send_sync
    super(ThreadedRequestsHTTPTransport, self).send(data, headers)
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\raven\transport\requests.py", line 41, in send
    timeout=self.timeout
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\requests\api.py", line 110, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\requests\api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\requests\sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\raven\breadcrumbs.py", line 297, in send
    resp = real_send(self, request, *args, **kwargs)
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\requests\sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\requests\adapters.py", line 479, in send
    raise ConnectTimeout(e, request=request)
ConnectTimeout: MaxRetryError: HTTPSConnectionPool(host='sentry.skipthe.net', port=443): Max retries exceeded with url: /api/8/store/ (Caused by ConnectTimeoutError('Connection to sentry.skipthe.net timed out. (connect timeout=1)'))
2018-03-04 20:57:18,483 - sentry.errors.uncaught           (27e8) :  ERROR (sentry.errors.uncaught:696) - [u'Exception raised in sync task: Bad Gateway - "Server unavailable"', u'  File "Plug-ins\\Trakttv.bundle\\Contents\\Libraries\\Shared\\plugin\\sync\\main.py", line 173, in run_wrapper', u'  File "Plug-ins\\Trakttv.bundle\\Contents\\Libraries\\Shared\\plugin\\sync\\main.py", line 260, in run', u'  File "Plug-ins\\Trakttv.bundle\\Contents\\Libraries\\Shared\\plugin\\sync\\main.py", line 277, in _trigger', u'  File "Plug-ins\\Trakttv.bundle\\Contents\\Libraries\\Shared\\elapsed\\main.py", line 64, in inner', u'  File "Plug-ins\\Trakttv.bundle\\Contents\\Libraries\\Shared\\plugin\\sync\\modes\\full.py", line 23, in start', u'  File "Plug-ins\\Trakttv.bundle\\Contents\\Libraries\\Shared\\elapsed\\main.py", line 64, in inner', u'  File "Plug-ins\\Trakttv.bundle\\Contents\\Libraries\\Shared\\plugin\\sync\\core\\task\\state\\trakt_.py", line 110, in refresh', u'  File "Plug-ins\\Trakttv.bundle\\Contents\\Libraries\\Shared\\trakt_sync\\cache\\main.py", line 39, in refresh', u'  File "Plug-ins\\Trakttv.bundle\\Contents\\Libraries\\Shared\\trakt_sync\\cache\\sources\\sync.py", line 41, in refresh', u'  File "Plug-ins\\Trakttv.bundle\\Contents\\Libraries\\Shared\\trakt\\interfaces\\base\\__init__.py", line 20, in wrap', u'  File "Plug-ins\\Trakttv.bundle\\Contents\\Libraries\\Shared\\trakt\\interfaces\\sync\\__init__.py", line 36, in last_activities', u'  File "Plug-ins\\Trakttv.bundle\\Contents\\Libraries\\Shared\\trakt\\interfaces\\base\\__init__.py", line 81, in get_data']
2018-03-04 20:58:58,117 - plugin.interface.m_sync          (498) :  INFO (plugin.interface.m_sync:1159) - Ignored duplicate sync trigger action
2018-03-04 20:58:58,118 - root                             (498) :  INFO (root:840) - 304 GET /video/trakt/sync/synchronize?account_id=1&t=1520193427.36 (127.0.0.1) 2.00ms
2018-03-04 20:58:58,142 - plex.objects.core.base           (660) :  WARNING (plex.objects.core.base:1171) - [Section] Omitted attribute: scannedat
2018-03-04 20:58:58,144 - plex.objects.core.base           (660) :  WARNING (plex.objects.core.base:1171) - [Section] Omitted attribute: scannedat
2018-03-04 20:58:58,147 - root                             (660) :  INFO (root:840) - 200 GET /video/trakt/sync?account_id=1 (127.0.0.1) 18.00ms
2018-03-04 20:58:58,223 - plugin.sync.main                 (1e5c) :  INFO (plugin.sync.main:1159) - (2) Started
2018-03-04 20:58:58,226 - plugin.sync.modes.core.base.mode (1e5c) :  INFO (plugin.sync.modes.core.base.mode:1159) - Executing construct() on child: <plugin.sync.modes.push.movies.Movies object at 0x08740970>
2018-03-04 20:58:58,232 - plex.objects.core.base           (1e5c) :  WARNING (plex.objects.core.base:1171) - [Section] Omitted attribute: scannedat
2018-03-04 20:58:58,233 - plex.objects.core.base           (1e5c) :  WARNING (plex.objects.core.base:1171) - [Section] Omitted attribute: scannedat
2018-03-04 20:58:58,233 - plugin.sync.modes.core.base.mode (1e5c) :  INFO (plugin.sync.modes.core.base.mode:1159) - Executing construct() on child: <plugin.sync.modes.push.shows.Shows object at 0x087407F0>
2018-03-04 20:58:58,240 - plex.objects.core.base           (1e5c) :  WARNING (plex.objects.core.base:1171) - [Section] Omitted attribute: scannedat
2018-03-04 20:58:58,240 - plex.objects.core.base           (1e5c) :  WARNING (plex.objects.core.base:1171) - [Section] Omitted attribute: scannedat
2018-03-04 20:58:59,194 - root                             (24c0) :  INFO (root:840) - 200 GET /video/trakt/sync/push?section=1&account_id=1&t=1520193437.27 (127.0.0.1) 1026.00ms
2018-03-04 20:58:59,223 - plex.objects.core.base           (1688) :  WARNING (plex.objects.core.base:1171) - [Section] Omitted attribute: scannedat
2018-03-04 20:58:59,224 - plex.objects.core.base           (1688) :  WARNING (plex.objects.core.base:1171) - [Section] Omitted attribute: scannedat
2018-03-04 20:58:59,227 - root                             (1688) :  INFO (root:840) - 200 GET /video/trakt/sync?account_id=1 (127.0.0.1) 17.00ms
2018-03-04 20:59:02,033 - trakt_sync.cache.sources.sync    (1e5c) :  INFO (trakt_sync.cache.sources.sync:1159) - Fetching "sync/ratings/episodes"
2018-03-04 20:59:04,490 - plugin.interface.m_sync          (354) :  INFO (plugin.interface.m_sync:1159) - Ignored duplicate sync trigger action
2018-03-04 20:59:04,493 - root                             (354) :  INFO (root:840) - 304 GET /video/trakt/sync/push?section=1&account_id=1&t=1520193437.27 (127.0.0.1) 4.00ms
2018-03-04 20:59:04,530 - plex.objects.core.base           (664) :  WARNING (plex.objects.core.base:1171) - [Section] Omitted attribute: scannedat
2018-03-04 20:59:04,533 - plex.objects.core.base           (664) :  WARNING (plex.objects.core.base:1171) - [Section] Omitted attribute: scannedat
2018-03-04 20:59:04,538 - root                             (664) :  INFO (root:840) - 200 GET /video/trakt/sync?account_id=1 (127.0.0.1) 18.00ms
2018-03-04 20:59:04,581 - plex.objects.core.base           (171c) :  WARNING (plex.objects.core.base:1171) - [Section] Omitted attribute: scannedat
2018-03-04 20:59:04,582 - plex.objects.core.base           (171c) :  WARNING (plex.objects.core.base:1171) - [Section] Omitted attribute: scannedat
2018-03-04 20:59:04,585 - root                             (171c) :  INFO (root:840) - 200 GET /video/trakt/sync?account_id=1&refresh=1520193539.21 (127.0.0.1) 17.00ms
2018-03-04 20:59:05,680 - plex.objects.core.base           (27c4) :  WARNING (plex.objects.core.base:1171) - [Section] Omitted attribute: scannedat
2018-03-04 20:59:05,681 - plex.objects.core.base           (27c4) :  WARNING (plex.objects.core.base:1171) - [Section] Omitted attribute: scannedat
2018-03-04 20:59:05,684 - root                             (27c4) :  INFO (root:840) - 200 GET /video/trakt/sync?account_id=1&refresh=1520193539.21 (127.0.0.1) 15.00ms
2018-03-04 20:59:05,732 - plex.objects.core.base           (848) :  WARNING (plex.objects.core.base:1171) - [Section] Omitted attribute: scannedat
2018-03-04 20:59:05,753 - plex.objects.core.base           (848) :  WARNING (plex.objects.core.base:1171) - [Section] Omitted attribute: scannedat
2018-03-04 20:59:05,756 - root                             (848) :  INFO (root:840) - 200 GET /video/trakt/sync?account_id=1&refresh=1520193544.57 (127.0.0.1) 44.00ms
2018-03-04 20:59:06,132 - trakt_sync.cache.sources.sync    (1e5c) :  INFO (trakt_sync.cache.sources.sync:1159) - Fetching "sync/ratings/seasons"
2018-03-04 20:59:06,783 - plex.objects.core.base           (1c18) :  WARNING (plex.objects.core.base:1171) - [Section] Omitted attribute: scannedat
2018-03-04 20:59:06,786 - plex.objects.core.base           (1c18) :  WARNING (plex.objects.core.base:1171) - [Section] Omitted attribute: scannedat
2018-03-04 20:59:06,789 - root                             (1c18) :  INFO (root:840) - 200 GET /video/trakt/sync?account_id=1&refresh=1520193544.57 (127.0.0.1) 18.00ms
2018-03-04 20:59:06,822 - plex.objects.core.base           (11f4) :  WARNING (plex.objects.core.base:1171) - [Section] Omitted attribute: scannedat
2018-03-04 20:59:06,825 - plex.objects.core.base           (11f4) :  WARNING (plex.objects.core.base:1171) - [Section] Omitted attribute: scannedat
2018-03-04 20:59:06,828 - root                             (11f4) :  INFO (root:840) - 200 GET /video/trakt/sync?account_id=1&refresh=1520193545.72 (127.0.0.1) 16.00ms
2018-03-04 20:59:07,433 - trakt_sync.cache.sources.sync    (1e5c) :  INFO (trakt_sync.cache.sources.sync:1159) - Fetching "sync/ratings/shows"
2018-03-04 20:59:07,744 - trakt.interfaces.base            (1e5c) :  WARNING (trakt.interfaces.base:48) - Request failed: "GET /sync/ratings/shows" - 502: "Server unavailable" (Bad Gateway)
2018-03-04 20:59:07,747 - plugin.sync.main                 (1e5c) :  WARNING (plugin.sync.main:1171) - Exception raised in sync task: Bad Gateway - "Server unavailable"
Traceback (most recent call last):
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\plugin\sync\main.py", line 173, in run_wrapper
    self.run()
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\plugin\sync\main.py", line 260, in run
    'stop'
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\plugin\sync\main.py", line 277, in _trigger
    func()
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\elapsed\main.py", line 64, in inner
    return func(*args, **kwargs)
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\plugin\sync\modes\push\__init__.py", line 29, in start
    self.trakt.refresh()
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\elapsed\main.py", line 64, in inner
    return func(*args, **kwargs)
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\plugin\sync\core\task\state\trakt_.py", line 110, in refresh
    self.changes = list(self.changes)
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\trakt_sync\cache\main.py", line 39, in refresh
    for result in source.refresh(username):
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\trakt_sync\cache\sources\sync.py", line 77, in refresh
    store = self.fetch(d, m)
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\trakt_sync\cache\sources\sync.py", line 165, in fetch
    return func(exceptions=True)
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\trakt\interfaces\base\__init__.py", line 20, in wrap
    return func(*args, **kwargs)
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\trakt\interfaces\sync\ratings.py", line 27, in shows
    return self.get('shows', store, rating, **kwargs)
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\trakt\interfaces\base\__init__.py", line 20, in wrap
    return func(*args, **kwargs)
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\trakt\interfaces\sync\ratings.py", line 18, in get
    **kwargs
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\trakt\interfaces\base\__init__.py", line 20, in wrap
    return func(*args, **kwargs)
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\trakt\interfaces\sync\core\mixins.py", line 30, in get
    items = self.get_data(response, **kwargs)
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\trakt\interfaces\base\__init__.py", line 81, in get_data
    raise ServerError(response)
ServerError: Bad Gateway - "Server unavailable"
2018-03-04 20:59:07,851 - plugin.core.backup.sources.database (1e5c) :  INFO (plugin.core.backup.sources.database:1159) - [trakt\1] Backing up database to u'C:\\Users\\Nuc\\AppData\\Local\\Plex Media Server\\Plug-in Support\\Data\\com.plexapp.plugins.trakttv\\Backups\\trakt\\1.bgr\\2018\\03\\04_205907_29.db'
2018-03-04 20:59:07,871 - plugin.sync.main                 (1e5c) :  INFO (plugin.sync.main:1159) - (2) Done
2018-03-04 20:59:08,137 - plex.objects.core.base           (2260) :  WARNING (plex.objects.core.base:1171) - [Section] Omitted attribute: scannedat
2018-03-04 20:59:08,138 - plex.objects.core.base           (2260) :  WARNING (plex.objects.core.base:1171) - [Section] Omitted attribute: scannedat
2018-03-04 20:59:08,141 - root                             (2260) :  INFO (root:840) - 200 GET /video/trakt/sync?account_id=1&refresh=1520193545.72 (127.0.0.1) 19.00ms
2018-03-04 20:59:08,174 - plex.objects.core.base           (2c4) :  WARNING (plex.objects.core.base:1171) - [Section] Omitted attribute: scannedat
2018-03-04 20:59:08,177 - plex.objects.core.base           (2c4) :  WARNING (plex.objects.core.base:1171) - [Section] Omitted attribute: scannedat
2018-03-04 20:59:08,180 - root                             (2c4) :  INFO (root:840) - 200 GET /video/trakt/sync?account_id=1&refresh=1520193546.82 (127.0.0.1) 18.00ms
2018-03-04 20:59:08,752 - sentry.errors                    (27e8) :  ERROR (sentry.errors:671) - Sentry responded with an error: MaxRetryError: HTTPSConnectionPool(host='sentry.skipthe.net', port=443): Max retries exceeded with url: /api/8/store/ (Caused by ConnectTimeoutError('Connection to sentry.skipthe.net timed out. (connect timeout=1)')) (url: https://sentry.skipthe.net/api/8/store/)
Traceback (most recent call last):
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\raven\transport\threaded_requests.py", line 26, in send_sync
    super(ThreadedRequestsHTTPTransport, self).send(data, headers)
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\raven\transport\requests.py", line 41, in send
    timeout=self.timeout
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\requests\api.py", line 110, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\requests\api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\requests\sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\raven\breadcrumbs.py", line 297, in send
    resp = real_send(self, request, *args, **kwargs)
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\requests\sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\requests\adapters.py", line 479, in send
    raise ConnectTimeout(e, request=request)
ConnectTimeout: MaxRetryError: HTTPSConnectionPool(host='sentry.skipthe.net', port=443): Max retries exceeded with url: /api/8/store/ (Caused by ConnectTimeoutError('Connection to sentry.skipthe.net timed out. (connect timeout=1)'))
2018-03-04 20:59:08,757 - sentry.errors.uncaught           (27e8) :  ERROR (sentry.errors.uncaught:696) - [u'Request failed: "GET /sync/ratings/shows" - 502: "Server unavailable" (Bad Gateway)']
2018-03-04 20:59:09,755 - sentry.errors                    (27e8) :  ERROR (sentry.errors:671) - Sentry responded with an error: MaxRetryError: HTTPSConnectionPool(host='sentry.skipthe.net', port=443): Max retries exceeded with url: /api/8/store/ (Caused by ConnectTimeoutError('Connection to sentry.skipthe.net timed out. (connect timeout=1)')) (url: https://sentry.skipthe.net/api/8/store/)
Traceback (most recent call last):
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\raven\transport\threaded_requests.py", line 26, in send_sync
    super(ThreadedRequestsHTTPTransport, self).send(data, headers)
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\raven\transport\requests.py", line 41, in send
    timeout=self.timeout
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\requests\api.py", line 110, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\requests\api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\requests\sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\raven\breadcrumbs.py", line 297, in send
    resp = real_send(self, request, *args, **kwargs)
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\requests\sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Nuc\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\requests\adapters.py", line 479, in send
    raise ConnectTimeout(e, request=request)
ConnectTimeout: MaxRetryError: HTTPSConnectionPool(host='sentry.skipthe.net', port=443): Max retries exceeded with url: /api/8/store/ (Caused by ConnectTimeoutError('Connection to sentry.skipthe.net timed out. (connect timeout=1)'))
2018-03-04 20:59:09,762 - sentry.errors.uncaught           (27e8) :  ERROR (sentry.errors.uncaught:696) - [u'Exception raised in sync task: Bad Gateway - "Server unavailable"', u'  File "Plug-ins\\Trakttv.bundle\\Contents\\Libraries\\Shared\\plugin\\sync\\main.py", line 173, in run_wrapper', u'  File "Plug-ins\\Trakttv.bundle\\Contents\\Libraries\\Shared\\plugin\\sync\\main.py", line 260, in run', u'  File "Plug-ins\\Trakttv.bundle\\Contents\\Libraries\\Shared\\plugin\\sync\\main.py", line 277, in _trigger', u'  File "Plug-ins\\Trakttv.bundle\\Contents\\Libraries\\Shared\\elapsed\\main.py", line 64, in inner', u'  File "Plug-ins\\Trakttv.bundle\\Contents\\Libraries\\Shared\\plugin\\sync\\modes\\push\\__init__.py", line 29, in start', u'  File "Plug-ins\\Trakttv.bundle\\Contents\\Libraries\\Shared\\elapsed\\main.py", line 64, in inner', u'  File "Plug-ins\\Trakttv.bundle\\Contents\\Libraries\\Shared\\plugin\\sync\\core\\task\\state\\trakt_.py", line 110, in refresh', u'  File "Plug-ins\\Trakttv.bundle\\Contents\\Libraries\\Shared\\trakt_sync\\cache\\main.py", line 39, in refresh', u'  File "Plug-ins\\Trakttv.bundle\\Contents\\Libraries\\Shared\\trakt_sync\\cache\\sources\\sync.py", line 77, in refresh', u'  File "Plug-ins\\Trakttv.bundle\\Contents\\Libraries\\Shared\\trakt_sync\\cache\\sources\\sync.py", line 165, in fetch', u'  File "Plug-ins\\Trakttv.bundle\\Contents\\Libraries\\Shared\\trakt\\interfaces\\base\\__init__.py", line 20, in wrap', u'  File "Plug-ins\\Trakttv.bundle\\Contents\\Libraries\\Shared\\trakt\\interfaces\\sync\\ratings.py", line 27, in shows', u'  File "Plug-ins\\Trakttv.bundle\\Contents\\Libraries\\Shared\\trakt\\interfaces\\base\\__init__.py", line 20, in wrap', u'  File "Plug-ins\\Trakttv.bundle\\Contents\\Libraries\\Shared\\trakt\\interfaces\\sync\\ratings.py", line 18, in get', u'  File "Plug-ins\\Trakttv.bundle\\Contents\\Libraries\\Shared\\trakt\\interfaces\\base\\__init__.py", line 20, in wrap', u'  File "Plug-ins\\Trakttv.bundle\\Contents\\Libraries\\Shared\\trakt\\interfaces\\sync\\core\\mixins.py", line 30, in get', u'  File "Plug-ins\\Trakttv.bundle\\Contents\\Libraries\\Shared\\trakt\\interfaces\\base\\__init__.py", line 81, in get_data']
`

**Comment by BlackyFox** [comment]
Sorry, I got it.
With last push, everything is working on my side too. 👍

**Comment by shwetkprabhat** [comment]
@rectifyer - I deleted and pulled the latest using WebTools, still the same issue.

**Comment by rectifyer** [comment]
@shwetkprabhat I haven't made any updates in regards to this bug. There should be an update to remove this code soon.

**Comment by animosity22** [comment]
So I'm perhaps more confused than when I started. It's working now and sentry.skipthe.net is still down. I and quite a few others that I've seen have been able to authenticate even with that site down.

**Comment by rectifyer** [comment]
Correct, the fix I made was in the Trakt API to fix the authentication. The `sentry.skipthe.net` is a separate issue and not related to the authentication issue.

**Comment by animosity22** [comment]
So the first part of the title/bug is fixed and the second part remains. Might be better to close this out and open a separate bug since the authentication bit is resolved.

**Comment by shwetkprabhat** [comment]
@rectifyer - yes thanks, able to sync now!

**Comment by vecchiae** [comment]
Thanks, I installed 1.3.3 and I am now also able to sync

**Comment by rectifyer** [comment]
v1.3.3 released and fixed both issues mentioned in this thread.
